---
- name: Render docker-compose config
  template:
    src: docker-compose.yml.j2
    dest: "{{ traefik_directory }}/docker-compose.yml"
  notify: start traefik

- name: Check that acme.json exists
  stat:
    path: "{{ traefik_directory }}/acme.json"
  when: traefik_acme_enable
  register: acme

- name: Ensure acme config
  file:
    path: "{{ traefik_directory }}/acme.json"
    state: touch
    mode: 0600
  when: acme.stat.exists == False

- name: Create traefik docker network
  docker_network:
    name: "{{ traefik_docker_network }}"
    state: present

- name: Pull docker image
  community.general.docker_image:
    name: traefik
    source: pull
    tag: "{{ traefik_version }}"
  notify: start traefik
