---
- name: start traefik
  community.general.docker_compose:
    state: present
    project_src: "{{ traefik_directory }}"

- name: restart traefik
  community.general.docker_compose:
    state: present
    project_src: "{{ traefik_directory }}"
    restarted: yes
